import React from 'react';

// --- 1. Robust Client-Side Download Function ---
// Handles external cross-origin images gracefully by trying a Blob fallback or opening in a new tab if blocked.
const handleDownload = async (url, filename) => {
  if (!url || url.includes('Placeholder+Image')) {
    alert("Cannot download: The asset URL is a generic placeholder or missing.");
    return;
  }
  
  try {
    const response = await fetch(url, { mode: 'cors' });
    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const blob = await response.blob();
    
    // Create an invisible link element to force download
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename || 'generated_ad_asset.bin'; 
    
    // Append to the document, click it, and clean up
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  } catch (error) {
    console.warn("Direct blob download failed due to CORS restrictions. Falling back to secure window open.", error);
    // Secure Fallback: Open in a new tab if cloud-storage provider blocks hot-linking
    const newWindow = window.open(url, '_blank');
    if (!newWindow) {
      alert("Popup blocked! Please allow popups to save your generated ad asset variations.");
    }
  }
};


function ResultsPage({ data, reset }) {
  const { images, videoUrl } = data;
  
  // A consistent placeholder image URL
  const PLACEHOLDER_IMG_URL = 'https://via.placeholder.com/300x200?text=Placeholder+Image';

  const handleNewAds = () => {
    reset(); 
  };

  if (!images || images.length === 0) {
    return (
      <div style={{ padding: '20px', textAlign: 'center' }}>
        <h2>No Results Found 😔</h2>
        <p>Please go back and generate ad concepts again.</p>
        <button onClick={handleNewAds} style={{ padding: '10px 20px', background: '#4f46e5', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', marginTop: '15px' }}>
          Start New Generation
        </button>
      </div>
    );
  }
  

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
      <header style={{ textAlign: 'center', marginBottom: '40px', borderBottom: '2px solid #e5e7eb', paddingBottom: '20px' }}>
        <h1 style={{ color: '#1f2937', fontSize: '2.5rem' }}>🎯 Ad Generation Results</h1>
        <p style={{ color: '#6b7280', fontSize: '1.1rem' }}>Concepts generated by **Google Gemini**</p>
      </header>
      
      {/* --- Image Ad Variations Section --- */}
      <h2 style={{ color: '#374151', marginBottom: '20px', borderLeft: '4px solid #4f46e5', paddingLeft: '15px' }}>🖼️ Image Ad Variations</h2>
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '30px',
          marginBottom: '40px',
        }}
      >
        {images.map((ad, index) => (
          <div
            key={index}
            style={{
              border: '1px solid #d1d5db',
              borderRadius: '12px',
              padding: '20px',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
              backgroundColor: '#fff',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
            }}
          >
            <div>
              <h3 style={{ color: '#111827', marginBottom: '10px', fontSize: '1.5rem' }}>Variation #{index + 1}</h3>
              <p style={{ color: '#9ca3af', fontSize: '0.85rem', marginBottom: '15px' }}>A/B Test ID: IMG-VAR-{index + 1}</p>

              {/* --- DISPLAY GENERATED COPY & PROMPT --- */}
              <div style={{ padding: '5px 0 15px', borderBottom: '1px solid #eee' }}>
                  <p style={{ fontWeight: '800', color: '#111827', fontSize: '1.1rem', margin: '0 0 5px 0' }}>{ad.headline}</p>
                  <p style={{ color: '#6b7280', fontSize: '0.9rem', margin: '0' }}>{ad.body}</p>
                  
                  {/* Image Prompt from Gemini */}
                  <p style={{ color: '#9ca3af', fontSize: '0.75rem', marginTop: '10px', fontStyle: 'italic', wordBreak: 'break-word' }}>
                      Prompt: {ad.image_prompt}
                  </p>
              </div>
              {/* --- END GENERATED COPY & PROMPT --- */}

              {/* Image Display */}
              <img
                src={ad.image_url || PLACEHOLDER_IMG_URL} 
                alt={`Ad Variation ${index + 1}`}
                style={{ width: '100%', height: 'auto', borderRadius: '8px', objectFit: 'cover', marginTop: '15px', minHeight: '150px' }}
                onError={(e) => { e.target.onerror = null; e.target.src = PLACEHOLDER_IMG_URL; }} 
              />
            </div>

            {/* --- Download Button --- */}
            <div style={{ marginTop: '20px' }}>
              <button
                onClick={() => handleDownload(ad.image_url || PLACEHOLDER_IMG_URL, `ad-variation-${index + 1}.jpg`)}
                style={{
                  width: '100%',
                  background: '#4f46e5',
                  color: '#fff',
                  padding: '10px 18px',
                  borderRadius: '8px',
                  fontSize: '15px',
                  fontWeight: '600',
                  cursor: 'pointer',
                  transition: 'background 0.3s',
                  border: 'none',
                }}
              >
                ⬇ Download Image
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* --- Video Ad Section --- */}
      <h2 style={{ color: '#374151', marginBottom: '20px', borderLeft: '4px solid #4f46e5', paddingLeft: '15px' }}>📹 Video Ad Concept</h2>
      <div style={{ border: '1px solid #d1d5db', borderRadius: '12px', padding: '20px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)', backgroundColor: '#fff' }}>
        
        <p style={{ color: '#6b7280', fontSize: '0.9rem', marginBottom: '20px' }}>
            **Video Concept:** (The video's final content relies on the detail of the generated prompt.)
        </p>
        
        {videoUrl && (
          <>
            <video width="100%" controls style={{ borderRadius: '8px', marginBottom: '20px' }}>
              <source src={videoUrl} type="video/mp4" />
              Your browser does not support the video tag.
            </video>
            <div style={{ marginTop: '10px', textAlign: 'center' }}>
                {/* Download Button for Video */}
                <button
                onClick={() => handleDownload(videoUrl, 'ad-video.mp4')}
                style={{
                    background: '#4f46e5',
                    color: '#fff',
                    padding: '12px 20px',
                    borderRadius: '8px',
                    fontSize: '16px',
                    fontWeight: '600',
                    cursor: 'pointer',
                    transition: 'background 0.3s',
                    border: 'none',
                    marginRight: '15px'
                }}
                >
                ⬇ Download Video
                </button>
                <p style={{color: '#9ca3af', fontSize: '0.75rem', marginTop: '10px'}}>*Video is currently a placeholder URL from the server.*</p>
            </div>
          </>
        )}
      </div>

      {/* --- New Ads Button --- */}
      <div style={{ textAlign: 'center', marginTop: '40px' }}>
        <button
          onClick={handleNewAds}
          style={{
            background: '#10b981',
            color: '#fff',
            padding: '12px 30px',
            borderRadius: '8px',
            fontSize: '16px',
            fontWeight: '700',
            cursor: 'pointer',
            transition: 'background 0.3s',
            border: 'none',
          }}
        >
          🚀 Generate New Ads
        </button>
      </div>
    </div>
  );
}

export default ResultsPage;
